Adding trunk
Automattic/vip-container-images pull request #201
Opened 2022-05-02 15:14 UTC by rinatkhaziev

high chance this won't work :)

2022-05-02 17:30 UTC, sjinks approved these changes

2022-05-02 17:33 UTC, sjinks requested changes

2022-05-02 17:33 UTC, sjinks commented on wordpress/versions.json
> +    "cacheable": true,
```suggestion
    "cacheable": false,
```

We should not cache "moving" targets. If `cacheable` is set to true, we will use Docker cache. In this case, Docker sees that the build arguments are the same and it will take all layers from its cache. It won't actually run any `git` commands, and we will end up having the old cached image.

2022-05-02 17:33 UTC, sjinks commented on wordpress/versions.json
> +    "cacheable": true,
In general, `cacheable: true` should only be set for stable things like tags which will never change.

2022-05-03 01:37 UTC, rinatkhaziev commented on wordpress/versions.json
> +    "cacheable": true,
good catch! I ran the script with the default args I think 😬

2022-05-03 06:10 UTC, sjinks approved these changes

2022-05-03 21:04 UTC, jesse-greathouse approved these changes

2022-05-03 21:35 UTC, merged