Explicitly defines which 2FA providers are able to be used in the dev…
Automattic/vip-container-images pull request #38
Opened 2021-11-01 21:09 UTC by jesse-greathouse

* Removes the use of the problem FIDO U2F 2FA provider while in the dev-env image

2021-11-02 06:19 UTC, pschoffer requested changes

2021-11-02 06:19 UTC, pschoffer commented on dev-tools/dev-env-plugin.php
> +add_filter('two_factor_providers', function() {
Awesomsouce! One minor suggestion would be to remove the unnecessary one instead of naming all the others. Sort of like we do here:

https://github.com/Automattic/vip-go-mu-plugins/blob/9d3bf1eb73c2f5dfa5909c2942cd5e75993029f4/wpcom-vip-two-factor/set-providers.php#L8

2021-11-02 06:21 UTC, pschoffer commented on dev-tools/dev-env-plugin.php
> +add_filter('two_factor_providers', function() {
So something like:
```
add_filter('two_factor_providers', function($providers) {
        unset( $providers['Two_Factor_FIDO_U2F'] );
	return $providers;
});

```

2021-11-02 12:57 UTC, jesse-greathouse commented on dev-tools/dev-env-plugin.php
> +add_filter('two_factor_providers', function() {
Very good. Thanks. I will make this change.

2021-11-03 22:43 UTC, sjinks approved these changes

2021-11-04 05:47 UTC, pschoffer approved these changes

2021-11-05 01:56 UTC, merged