Add WP Test Runner image
Automattic/vip-container-images pull request #39
Opened 2021-11-04 18:08 UTC by sjinks

This PR adds a new image to run CI tests for WordPress using CircleCI as the provider.

The image features:
* latest WP versions since WP 5.5 + trunk (updated daily)
* PHP 7.4, 8.0, 8.1
* PHPUnit 7, 8, 9 (latest versions)
* NodeJS 14, npm 6
* Subversion

The image is used in a test branch of [vip-go-mu-plugins](Automattic/vip-go-mu-plugins#2544). Its main advantages are that it reduces the CI time by providing all dependencies baked into the image and that it reduces the load on WP.org SVN (which sometimes rate-limits us).

Even though it is used by `vip-go-mu-plugins`, it can be used with any WP plugin (I use it myself for my plugins).

2021-11-04 18:09 UTC, sjinks commented on .github/workflows/wp-test-runner.yml
> +    - cron: '45 10 * * *'
Adding a schedule here because the `trunk` WordPress is not static.

2021-11-04 18:10 UTC, sjinks commented on .github/workflows/wp-test-runner.yml
> +      - ".github/workflows/wp-test-runner.yml"
This helps avoid unnecessary builds; the image is built only when one of its files gets changed, or when this workflow gets updated.

2021-11-04 18:10 UTC, sjinks commented on .github/workflows/wp-test-runner.yml
> +  workflow_dispatch:
A convenient way to be able to trigger the workflow manually :-)

2021-11-04 18:13 UTC, sjinks commented on wp-test-runner/Dockerfile
> +RUN install-wp trunk
Moved this to a separate `RUN` because the stable WP branches don't change very often. Oftentimes, this layer will be the only change in the image. This will allow us to save some space (Docker will notice that the rest of the layers already exist and don't need to be updated).

2021-11-04 18:14 UTC, sjinks commented on wp-test-runner/runner
> +fi
This allows us to switch between PHP versions painlessly.

2021-11-04 18:44 UTC, pauarge requested changes
We purposely don't want to use CircleCI on this repo. We should try to stick with GitHub Actions.

2021-11-05 09:14 UTC, pschoffer approved these changes
:rocket:

2021-11-08 10:09 UTC, pauarge commented on .github/workflows/wp-test-runner.yml
> +  workflow_dispatch:
IMO I would rather not have the option to trigger the workflow manually. I see the use of it, but I'd rather have less code and less ways to do a thing than cover for very rare occurrences that we might need this.

2021-11-08 10:11 UTC, pauarge requested changes
Looks very good and it will be a good win for our CI. Left some nit-picks.

2021-11-08 10:11 UTC, pauarge commented on .github/workflows/wp-test-runner.yml
> +        uses: actions/checkout@v2.3.5
I'd pin to a less strict version, something like `checkout@v2`

2021-11-08 10:11 UTC, pauarge commented on .github/workflows/wp-test-runner.yml
> +          platforms: linux/amd64
I don't think we explicitly need to define the platform if we're just building for x64.

2021-11-08 11:13 UTC, sjinks commented on .github/workflows/wp-test-runner.yml
> +        uses: actions/checkout@v2.3.5
Fixed in 1c38a28

2021-11-08 11:14 UTC, sjinks commented on .github/workflows/wp-test-runner.yml
> +          platforms: linux/amd64
Fixed in 1c38a28

2021-11-08 12:13 UTC, pauarge approved these changes

2021-11-08 12:35 UTC, merged