Disable xdebug
Automattic/vip-container-images pull request #4
Opened 2021-08-20 13:49 UTC by pschoffer

This "disables" xdebug unles env variable `XDEBUG=enable`.

I am not sure if removing xdebug.ini is the best way, but it gets away with the warning at least.

2021-08-20 14:04 UTC, pauarge requested changes
Looks good, I left some minor functionality and naming changes.

2021-08-20 14:04 UTC, pauarge commented on php-fpm/Dockerfile
> +COPY php-fpm/xdebug.ini /usr/local/php/docker-php-ext-xdebug.ini
Instead of moving it to a different location, I would name the file `docker-php-ext-xdebug.ini.template` (I suggest template, but really anything can do).

2021-08-20 14:04 UTC, pauarge commented on php-fpm/Dockerfile
> +COPY php-fpm/run-php-fpm.sh /usr/local/bin/run-php-fpm.sh
What about naming it `run.sh`, given that we're in the context of php-fpm already? There are other images in Lando that use that convention.

2021-08-20 14:04 UTC, pauarge commented on php-fpm/run-php-fpm.sh
> +    cp $XDEBUG_CONFIG_LOCATION $XDEBUG_CONFIG_TARGET_LOCATION
I would move instead of copy.

2021-08-23 09:52 UTC, pschoffer commented on php-fpm/run-php-fpm.sh
> +    cp $XDEBUG_CONFIG_LOCATION $XDEBUG_CONFIG_TARGET_LOCATION
I copied because we `rm` the target. So if for some reason you would disable Xdebug and then within the same container (stopped maybe) would like to reenable you would have nowhere to take the file from.

But I am not sure if that scenario makes sense.

2021-08-23 09:55 UTC, pschoffer commented on php-fpm/Dockerfile
> +COPY php-fpm/xdebug.ini /usr/local/php/docker-php-ext-xdebug.ini
fixed

2021-08-23 09:55 UTC, pschoffer commented on php-fpm/Dockerfile
> +COPY php-fpm/run-php-fpm.sh /usr/local/bin/run-php-fpm.sh
fixed

2021-08-23 12:29 UTC, pauarge commented on php-fpm/Dockerfile
> +COPY php-fpm/xdebug.ini /usr/local/php/conf.d/docker-php-ext-xdebug.ini.template
```suggestion
COPY php-fpm/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.template
```

2021-08-23 12:30 UTC, pauarge commented on php-fpm/run.sh
> +XDEBUG_CONFIG_TEMPLATE_LOCATION=/usr/local/php/conf.d/docker-php-ext-xdebug.ini.template
```suggestion
XDEBUG_CONFIG_TEMPLATE_LOCATION=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.template
```

2021-08-23 12:45 UTC, pauarge approved these changes
LGTM

2021-08-23 12:54 UTC, merged