Dev-tools: Configure for subdirectory usage
Automattic/vip-container-images pull request #466
Opened 2023-04-17 16:44 UTC by rebeccahum

To play nice with https://github.com/Automattic/vip-cli/pull/1334

2023-04-18 06:46 UTC, pschoffer requested changes
Looks good.

We probably should also bump the dev-tools verision [here](https://github.com/Automattic/vip-container-images/blob/master/.github/workflows/dev-tools.yml#L57) that way existing dev-envs that send in the positional arguments will continue to work fine. (after that in you CLI PR - you can change [this line](https://github.com/Automattic/vip-cli/blob/develop/assets/dev-env.lando.template.yml.ejs#L17) to use your new dev-tools moving forward)


Also using `getopt` might be beneficial for doing that argument parsing, but it would not help that much on the full name options, and I think those are good as they sort of self-document. So probably just ignore this `getopt` point:)

2023-04-18 08:18 UTC, sjinks commented
We can check whether the first command line parameter starts with `--`. If it does, we use `getopt`. If it doesn't, we fall back to the old scheme with positional parameters.

@pschoffer, @rebeccahum what do you think?

2023-04-18 08:20 UTC, sjinks commented on dev-tools/setup.sh
>  if [ $# -lt 4 ]; then
I am afraid this won't work as expected :-( We now have 8 required parameters: `--host`, `<host>`, `--user`, `<user>`, `--domain`, `<domain>`, `--title`, `<title>`.

2023-04-18 15:02 UTC, rebeccahum commented
@sjinks @pschoffer My only question now is, what if someone has a new version of VIP-CLI with an old container image where it attempts to pass in the long form arguments where the script doesn't know them yet?

2023-04-18 15:10 UTC, sjinks commented
@rebeccahum I would say we need to wait for a couple of weeks until we merge the vip-cli PR.

2023-04-19 14:49 UTC, sjinks approved these changes

2023-04-19 14:52 UTC, merged