Retry Elasticsearch cluster healthcheck
Automattic/vip-container-images pull request #479
Opened 2023-05-09 14:40 UTC by pschoffer

We currently don't retry on failed ES check, which beats the purpose of the while loop.

2023-05-09 14:50 UTC, rebeccahum requested changes

2023-05-09 14:50 UTC, rebeccahum commented on dev-tools/setup.sh
> +  while ! curl -s 'http://elasticsearch:9200/_cluster/health' > /dev/null && [ "${second}" -lt 60 ]; do
Do we want a limit to the retries?

2023-05-09 14:53 UTC, sjinks commented on dev-tools/setup.sh
> +  while ! curl -s 'http://elasticsearch:9200/_cluster/health' > /dev/null && [ "${second}" -lt 60 ]; do
Yes, I missed that part.

2023-05-09 14:55 UTC, sjinks commented on dev-tools/setup.sh
> +  while ! curl -s 'http://elasticsearch:9200/_cluster/health' > /dev/null && [ "${second}" -lt 60 ]; do
It's like https://github.com/Automattic/vip-container-images/blob/91ad5f152d20a031a23bad9ab29d2fa73275f501/dev-tools/setup.sh#L104-L107

2023-05-09 14:55 UTC, sjinks approved these changes

2023-05-12 13:42 UTC, pschoffer commented
I added a dot-adder to show it is in progress.

2023-05-12 13:46 UTC, sjinks approved these changes

2023-05-12 13:47 UTC, merged